const menu = [
  {
    id: 1,
    title: "Tteokbokki",
    category: "Korea",
    price: 10.99,
    img: "https://twoplaidaprons.com/wp-content/uploads/2020/09/tteokbokki-top-down-view-of-tteokbokki-in-a-bowl-500x500.jpg",
    desc: `Spicy rice cakes, serving with fish cake.`,
  },
  {
    id: 2,
    title: "Chicken Ramen",
    category: "Japan",
    price: 7.99,
    img: "https://www.forkknifeswoon.com/wp-content/uploads/2014/10/simple-homemade-chicken-ramen-fork-knife-swoon-01.jpg",
    desc: `Chicken noodle soup, serving with vegetables such as soy bean, green onion. In an optional you can ask for egg. `,
  },
  {
    id: 3,
    title: "Bibimbap",
    category: "Korea",
    price: 8.99,
    img: "https://dwellbymichelle.com/wp-content/uploads/2020/05/DWELL-bibimbap.jpg",
    desc: `Boiling vegetables, serving with special hot sauce`,
  },
  {
    id: 4,
    title: "Dan Dan Mian",
    category: "China",
    price: 5.99,
    img: "https://takestwoeggs.com/wp-content/uploads/2022/02/Dan-Dan-Noodles-Dan-Dan-Mian-5overhead-sq.jpg",
    desc: `Dan dan noodle, serving with green onion `,
  },
  {
    id: 5,
    title: "Yangzhou Fried Rice",
    category: "China",
    price: 12.99,
    img: "https://salu-salo.com/wp-content/uploads/2013/02/Yangzhou-Fried-Rice1.jpg",
    desc: `Yangzhou style fried rice, serving with bean and pickles `,
  },
  {
    id: 6,
    title: "Onigiri",
    category: "Japan",
    price: 9.99,
    img: "https://www.manusmenu.com/wp-content/uploads/2017/08/Onigiri-3-1-of-1.jpg",
    desc: `Rice Sandwich, serving with soy sauce`,
  },
  {
    id: 7,
    title: "Jajangmyeon",
    category: "Korea",
    price: 15.99,
    img: "https://www.curiouscuisiniere.com/wp-content/uploads/2020/04/Jajangmyeon-Korean-Noodles-in-Black-Bean-Sauce5.1200H-720x540.jpg",
    desc: `Black bean sauce noodle, serving with green onion `,
  },
  {
    id: 8,
    title: "Ma Yi Shang Shu",
    category: "China",
    price: 12.99,
    img: "https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/F688C2F6-86EC-46C4-B9C7-A6BA01DF7437/Derivates/32E3E72A-F786-406D-AF7F-B30980A9AC6C.jpg",
    desc: `Hot pepper sauce noodle, serving with soy bean and onion`,
  },
  {
    id: 9,
    title: "Doroyaki",
    category: "Japan",
    price: 3.99,
    img: "https://www.justonecookbook.com/wp-content/uploads/2011/10/Dorayaki-New-500x400.jpg",
    desc: `Red bean paste dessert, serving with honey.`,
  },
  {
    id: 10,
    title: "Lahmacun",
    category: "Turkiye",
    price: 2.99,
    img: "https://cdn.yemek.com/mnresize/1250/833/uploads/2020/04/lahmacun-yemekcom-1.jpg",
    desc: `İncecik açılmış hamur üzerine kıyma, baharatlar ve sebzelerle hazırlanan geleneksel lahmacun.`,
  },
  {
    id: 11,
    title: "İskender",
    category: "Turkiye",
    price: 3.99,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUathzpYXsFOoTkWrokc1oUMu8m1ZB3NnxjA&s",
    desc: `Tereyağlı, yoğurtlu, domates soslu ve dönerle servis edilen, Bursa'ya özgü meşhur bir yemek.`,
  },
  {
    id: 12,
    title: "Pide",
    category: "Turkiye",
    price: 2.99,
    img: "https://images.deliveryhero.io/image/fd-tr/LH/kjgx-hero.jpg?width=512&height=384&quality=45",
    desc: `Odun ateşinde pişirilen, ince hamur üzerinde peynir, kıyma ya da sucuk ile hazırlanan geleneksel pide.`,
  },
  {
    id: 13,
    title: "Mantı",
    category: "Turkiye",
    price: 3.99,
    img: "https://i.lezzet.com.tr/images-xxlarge-secondary/manti-nasil-pisirilir-9853d099-517c-4e89-be1c-960b703dcb8e.jpg",
    desc: `Küçük hamur parçalarının içine et konularak yapılan, yoğurt ve sarımsak sosuyla servis edilen Mantı.`,
  },
  {
    id: 14,
    title: "Adana Kebap",
    category: "Turkiye",
    price: 3.99,
    img: "https://turkishfoodie.com/wp-content/uploads/2018/11/Adana-Kebab-.jpg",
    desc: "Adana'ya özgü, zırhta çekilen etten yapılan baharatlı kebap, közlenmiş biber ve soğanla servis edilir.",
  },
  {
    id: 15,
    title: "Baklava",
    category: "Turkiye",
    price: 4.99,
    img: "https://www.gunduzoglu.com.tr/UserFiles/Fotograflar/org/109-fistikli-baklava-fistikli-baklava-fistikli-baklava.jpg",
    desc: "İnce açılan yufkaların arasına konulan ceviz ya da fıstık ile hazırlanan şerbetli tatlı, Türk mutfağının en özel lezzetlerinden.",
  },
];

export { menu };
